[build]
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/functions/*"
  to = "/functions/:splat"
  status = 200

[dev]
  functions = "functions"
  publish = "public"